services:
  triangulation_build:
    build: .
    network_mode: host
    volumes:
      - ./:/project_source/:ro
      - ./bin:/project/build/bin:rw
    command: ["/bin/bash","/project/docker/entrypoint.sh"]