name: building_environment

services:
  triangulation_build:
    build: .
    network_mode: host
    volumes:
      - ./:/project/:ro
      - ./bin:/project/build_dir/install/bin:rw
    command: ["/bin/bash","/project_source/docker/entrypoint.sh"]