name: building_environment

services:
  triangulation_build:
    build: .
    network_mode: none
    volumes:
      - ./:/project_source/:ro
      - ./build:/project/common_build_dir/:rw
    command: ["/bin/bash","/project_source/docker/entrypoint.sh"]