name: build_test.yml
on:
  push:
    paths-ignore:
      - "docs"
      - ".idea"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build_binary:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile
        run: |
          DOCKER_CONTAINER="echo "${{IMAGE_NAME}}" | tr '[:upper:]' '[:lower:]'"
          docker run -v "./:/project_source/:ro" -v "./build:/project/common_build_dir/:rw"  --entrypoint="/project_source/docker/entrypoint.sh"  --network=host ${{ env.REGISTRY }}/${DOCKER_CONTAINER}

      - name: install dependencies for running
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libcgal-qt5-dev \
          libcgal-dev

      - name: Test
        run: |
          ./build/build_dir/install/bin/polygon_triangulation --b=0.125 --size=5
          ./build/build_dir_debug/install/bin/polygon_triangulation --b=0.125 --size=5

